* Project Specifications

This project will be built using Django (the Python web application framework). It will include an administration panel allowing the site administrator to manage site information.


** Page Descriptions

- All "Contact Us" buttons should redirect to WhatsApp or sms. The user will be asked to choose.

  
*** Admin Page

- Admin should be able to change the information of the residences.
- Admin should be able to add new residences
- Admin should be able to delete residences
- Admin should be able to change the contact number


*** Navigation Bar

- Company logo (clicking it should lead to the homepage)
- "Home" link to the homepage
- "Reservation" page (listing residences)
- About Us, that will send to the part of the homepage that talks about the services
- Display contact information in the middle of the nav bar.

  
*** Footer

- Company logo (same behavior as the nav bar)
- Some social networks icons
- The phone number of the company
- Navigation tree for the pages of the site

  
*** Homepage

- Display a description of Ivoire Résidences' services.
- A scrolling section showcasing some residences
  + A button to "Show More" (leading to *the page displaying all residences (Reservation Page)*)
- A button to display the complete list (also in the navigation bar).
- A modal that permit to contact the company. The modal will redirect to whatsapp/sms with a template message ready and completed with the user information.

**** Contact modal

Will redirect to whatsapp/sms (asking before to the user) with the client's name and the message filled in the text section, building a ready to send message to whatsapp or sms.

- Nom (the lastname of the client)
- Prénoms (the first names of the client)
- Votre message (the message that will be sent to the company phone number)

  
*** Reservation Page

This page shows the complete list of the residences available. Only a limited number of residences will get displayed on each page.

- There should be a page navigation feature at the bottom of the page. Some numbers to quickly change the page.

- Filter fields at the top to filter results based on location (*Yamoussoukro enabled by default for now*) and reservation date, to show only available residences.
  
- Prices should display both promotional and regular prices.

- The user should be able to filter by the number of rooms they needs.

- Should also be able to filter by their budget.
  + 50 000   FCFCA - 100 000 FCFCA
  + 100 000  FCFCA - 150 000 FCFCA
  + 150 000  FCFCA - 200 000 FCFCA
  + 200 000  FCFCA - 250 000 FCFCA
  + 250 000+ FCFCA 

- Allow searching by name (with a button to initiate the search within the results).

- Show the project the residence that are already occupied in transparent gray with the ending time of the reservation.

** Models

*** Residence

- name (CharField)
- location (CharField, default: Yamoussoukro)
- description (TextField)
- rooms (IntegerField)
- price (IntegerField)
- promotional_price (IntegerField, nullable)
- is_available (boolean)
- next_availability (DateField, nullable)
- image (ImageField)

