# Generated by Django 4.2.19 on 2025-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(default='Yamoussoukro', max_length=255)),
                ('description', models.TextField()),
                ('rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('promotional_price', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('next_availability', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='residence_images/')),
            ],
        ),
    ]
