# Generated by Django 4.2.19 on 2025-03-10 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='rooms',
            new_name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='image',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='name',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='next_availability',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='promotional_price',
        ),
        migrations.AlterField(
            model_name='residence',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='residence',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="Administrator's phone number", max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
