# Generated by Django 4.2.19 on 2025-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_alter_residence_promotional_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='promotional_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
